---
- name: Ubuntu Install sshd
  apt:
      name: [ openssh-server ]
      state: present
  when: (ansible_distribution == "Ubuntu")

- name: enable root access
  vars:
    sshd_PermitRootLogin: 'yes'
    sshd_PasswordAuthentication: 'yes'
  include_role:
    name: ypsman.sshd_config
