---
- name: jetbrains toolbox
  include_role:
    name: jaredhocutt.jetbrains_toolbox
    apply:
      vars:
        ansible_become: false

- include: full_remote_mode.yml
  when: jetbrains_full_remote|bool
